apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: azure-cni
  namespace: kube-system
  labels:
    app: azure-cni
spec:
  selector:
    matchLabels:
      k8s-app: azure-cni
  template:
    metadata:
      labels:
        k8s-app: azure-cni
      annotations:
        cluster-autoscaler.kubernetes.io/daemonset-pod: "true"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.azure.com/cluster
                operator: Exists
              - key: type
                operator: NotIn
                values:
                - virtual-kubelet
              - key: beta.kubernetes.io/os
                operator: In
                values:
                - linux
      priorityClassName: system-node-critical
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - operator: "Exists"
          effect: NoExecute
        - operator: "Exists"
          effect: NoSchedule
      initContainers:
        - name: azure-cni
          image: acnpublic.azurecr.io/cni-dropgz:v1.4.28-41-g3ecb7fb1
          imagePullPolicy: Always
          command: ["/dropgz"]
          args:
            - deploy
            - azure-vnet
            - -o
            - /opt/cni/bin/azure-vnet
            - azure-linux-swift.conflist
            - -o 
            - /etc/cni/net.d/10-azure.conflist
          volumeMounts:
            - name: cni-bin
              mountPath: /opt/cni/bin
            - name: cni-conflist
              mountPath: /etc/cni/net.d
      containers:
        - name: pause
          image: k8s.gcr.io/pause:2.0
      hostNetwork: true
      volumes:
        - name: cni-conflist
          hostPath:
            path: /etc/cni/net.d
            type: Directory
        - name: cni-bin
          hostPath:
            path: /opt/cni/bin
            type: Directory
