---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.2
  creationTimestamp: null
  name: clustersubnetstates.acn.azure.com
spec:
  group: acn.azure.com
  names:
    kind: ClusterSubnetState
    listKind: ClusterSubnetStateList
    plural: clustersubnetstates
    singular: clustersubnetstate
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.exhausted
      name: Exhausted
      type: string
    - jsonPath: .spec.timestamp
      name: Updated
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ClusterSubnetState is the Schema for the ClusterSubnetState API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          status:
            description: ClusterSubnetStateStatus defines the observed state of ClusterSubnetState
            properties:
              exhausted:
                type: boolean
              timestamp:
                type: string
            required:
            - exhausted
            - timestamp
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
