---
apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-npm-config
  namespace: kube-system
data:
  azure-npm.json: |
    {
        "ResyncPeriodInMinutes": 15,
        "ListeningPort":         10091,
        "ListeningAddress":      "0.0.0.0",
        "Toggles": {
            "EnablePrometheusMetrics": true,
            "EnablePprof":             true,
            "EnableHTTPDebugAPI":      true,
            "EnableV2NPM":             false,
            "PlaceAzureChainFirst":    false
        },
        "Transport": {
          "Address": "azure-npm.kube-system.svc.cluster.local"
          "Port": 10092,
          "ServicePort": 9001
        }
    }
